
services:
  postgres:
    image: postgres:14-alpine
    container_name: flash_sale_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=flash_sale_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d flash_sale_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: flash_sale_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-node-1:
    build: .
    container_name: flash_sale_app_1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/flash_sale_db?reWriteBatchedInserts=true
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_SQL_INIT_MODE=always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 40s

  app-node-2:
    build: .
    container_name: flash_sale_app_2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/flash_sale_db?reWriteBatchedInserts=true
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_SQL_INIT_MODE=never
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      app-node-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: flash_sale_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app-node-1:
        condition: service_healthy
      app-node-2:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
