events {
    worker_connections 1024;
}

http {
    upstream flash_sale_backend {
        # Round-robin load balancing
        server app-node-1:8080;
        server app-node-2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://flash_sale_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
